name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pandas=1.2.3
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - pyyaml=5.4.1
  - protobuf=3.19.6
  - numpy=1.19.5
  - pip:
      - wandb==0.10.21
