name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pandas=1.2.3
  - matplotlib=3.3.4
  - pyyaml=5.4.1
  - pip:
      - wandb==0.10.21
